### ISSUE TITLE
Error when adding vazco:universe-autoform-select package using aldeed:autoform@5.1.2

### ISSUE THREAD

**Issue by Rongky** [vazco/meteor-universe-autoform-select#1]
=> Errors while adding packages:             

While selecting package versions:
error: Conflict: Constraint aldeed:autoform@4.0.0 is not satisfied by aldeed:autoform 5.1.2.
Constraints on package "aldeed:autoform":
- aldeed:autoform@5.1.2 <- top level
- aldeed:autoform@4.0.0 || 5.0.0 <- aldeed:autoform-bs-datepicker 1.1.1
- aldeed:autoform@4.0.0 <- vazco:universe-autoform-select 0.0.6

**Comment by MichalW** [comment]
Thanx - fixed
