### ISSUE TITLE
How to limit number of selected items?

### ISSUE THREAD

**Issue by wietsevr** [vazco/meteor-universe-autoform-select#10]
Thanks for the code - works like a charm.

I accept multiple items at the moment, but I'd need to limit the number of items accepted to a maximum. Anyone who can help me? Thanks :)

**Comment by MichalW** [comment]
hmm. I think You can add event:

```
'change select': function (e) 
```

and check in this function length of elements: `$(e.target).val().length`

**Comment by wietsevr** [comment]
I'll try it out, thanks for your help.

**Comment by rizafahmi** [comment]
@MichalW I did add an event and check the length of elements. But I have no idea what to do next. Please help.

```
  'change select': function (e) {
    var number_selected = $(e.target).val().length;

    if (number_selected >= 2) {
      // what to do?
    }

  }
```

**Comment by MichalW** [comment]
@wietsevr: @rizafahmi: I added just new option: 'values_limit'. Please look at the readme and test

**Comment by rizafahmi** [comment]
Nice @MichalW . Thanks for this package!
