### ISSUE TITLE
Placeholder is not working

### ISSUE THREAD

**Issue by rizafahmi** [vazco/meteor-universe-autoform-select#11]
I'm doing this in autoform:

```
      autoform: {
        type: "universe-select",
        placeholder: "Select one or two lab(s) to which your idea belongs.",
        ...
```

But the placeholder is not shown on the template.

<img width="756" alt="screen shot 2015-09-29 at 10 13 09 pm" src="https://cloud.githubusercontent.com/assets/1147918/10168539/8398cad8-66f7-11e5-8c38-b69fdd087ee0.png">

**Comment by skirunman** [comment]
Same issue here using:
`{{> afQuickField name='contactName' type="universe-select" options=options multiple=false placeholder='enter name'}}`

Quick perusal of code and don't see anywhere that placeholder is supported, but maybe I missed it.

**Comment by MichalW** [comment]
I added placeholder in new version

**Comment by rizafahmi** [comment]
@MichalW thanks for this. But unfortunately, the placeholder is not showing.

Am I doing it wrong?

```
autoform: {
        type: "universe-select",
        placeholder: "Select one or two lab(s) to which your idea belongs.",
        ...
```

**Comment by skirunman** [comment]
Nor for me.

**Comment by MichalW** [comment]
@skirunman This option is override by autoforms. I create new option "uniPlaceholder". Please update universe-autoform-select and try like this:

```
autoform: {
            afFieldInput: {
                type: 'universe-select',
                options: options,
                uniPlaceholder: 'Please select value'
            }
        }
```

**Comment by skirunman** [comment]
thanks @MichalW
