### ISSUE TITLE
"Field is necessary" when updating

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [vazco/meteor-universe-autoform-select#12]
Hello, when I have an update form with some values coming from the DB, I can't submit the form because it says that the field is necessary...
![bug universe](https://cloud.githubusercontent.com/assets/12840136/10250501/8868dd62-6901-11e5-88fe-7b8eebceabd8.png)

**Comment by MichalW** [comment]
If the problem persists in the latest version?
