### ISSUE TITLE
How to get uniPlaceholder to hide on text input

### ISSUE THREAD

**Issue by skirunman** [vazco/meteor-universe-autoform-select#14]
Thanks for adding uniPlaceholder in resolved issue #11. 

I would like uniPlaceholder to behave like standard HTML5 <input> placeholder attribute, i.e. be hidden on when user inputs text. This is how I believe other autoform input types that accept a placeholder behave. FYI, I'm using Meteoric Autoform on mobile. Right now it looks like uniPlaceholder is handled as

```
<div class="universe-autoform-select-placeholder">My PlacerHolder Name</div>
<input type="text" autocomplete="off" tabindex="">
```

when ideally i would like it be be like 
`<input type="text" autocomplete="off" tabindex="" placeholder="My Placeholder">`

Also, looks like Select2 supports this type of placeholder. https://select2.github.io/examples.html#placeholders

I'm not much of a css guy but if this functionality can be achieved with out changing your existing code please let me know.

Thanks a bunch!

**Comment by MichalW** [comment]
Please check it in the latest version 0.3.1
