### ISSUE TITLE
Problem with arrow key (up and down) to select item.

### ISSUE THREAD

**Issue by thearabbit** [vazco/meteor-universe-autoform-select#19]
Problem with arrow key (up and down) to select item.

**Comment by izakfilmalter** [comment]
I have added arrow support to my fork of this package along with other improvements: https://github.com/tuulbox/autoform-selectize

**Comment by thearabbit** [comment]
Good  job,  I will check to `https://github.com/tuulbox/autoform-selectize`

**Comment by MichalW** [comment]
Please check it in the latest version 0.3.1

**Comment by thearabbit** [comment]
Now It still have some problem with `arrow and tap key`.
Sorry, I opened the issue `#24`
