### ISSUE TITLE
Create form with autosave=true only updates once

### ISSUE THREAD

**Issue by nonissue** [vazco/meteor-universe-autoform-select#2]
Hey,

Playing around with this in my code, but also recreated it with the demo. Basically, with the "create" form with autosave=true, if you add/delete content and then mouse away, the changes you made are stored and the testObject.create is updated. If you again attempt to make changes on page without refreshing, any changes do not affect testObject.create and are not persistent after a refresh.

If this doesn't make sense, let me know.

**Comment by MichalW** [comment]
Is ok with autosave="false"? I think problem is with autosave in autoform and not only in "create".
