### ISSUE TITLE
"optionsMethodParams" support function callback?

### ISSUE THREAD

**Issue by thearabbit** [vazco/meteor-universe-autoform-select#22]
I would to change the `options value` depend on `other field` changed.

``` js
dependField: {
.......
}
.........
fundId: {
        type: [String],
        label: 'Fund',
        autoform: {
            type: 'universe-select',
            afFieldInput: {
                multiple: true,
                optionsMethod: 'loan_listFundOnProduct',
                optionsMethodParams: function(){
                  var dependField = AutoForm.getFieldValue('dependField');
                  return {dependField: dependField};
               }
            }
        }
    }
```

So I need `optionsMethodParams` to support function callback?
Please help me.

**Comment by MichalW** [comment]
Please try version 0.2.1, I allowed to use the function in optionsMethodParams

**Comment by thearabbit** [comment]
Thanks for quickly reply.
I love this package, because I have many problem with `select dropdown` that get data from the server.
Excuse me, could you solve `issue #19` to use arrow key to select item list.

**Comment by thearabbit** [comment]
Now it work fine, but it don't reactive to change params to server when I change value of `AutoForm.getFieldValue('dependField')`;

**Comment by MichalW** [comment]
I'm working on a big refactoring this package - please few more days of patience :)

**Comment by MichalW** [comment]
About `AutoForm.getFieldValue('dependField');`
I think you should create `new ReactiveVar` for this and use Tracker.autorun

**Comment by thearabbit** [comment]
I waiting you...
Could you example for reactive?
My schema:

``` js
fieldA: {
type: String,
        label: 'Field A',
        autoform: {
            type: 'universe-select',
            afFieldInput: {
                optionsMethod: 'getA'
            }
        }
}
.........
fieldBDependOnFieldA: {
        type: String,
        label: 'Field B Depend On Field A',
        autoform: {
            type: 'universe-select',
            afFieldInput: {
                optionsMethod: 'getBDependOnFieldA',
                optionsMethodParams: function(){
                  var fieldA= AutoForm.getFieldValue('fieldA');
                  return {fieldA: fieldA};
               }
            }
        }
    }
```

**Comment by thearabbit** [comment]
I tried again, the value of `fieldA` is reactive when it change, but the `optionsMethodParams` don't pass the new value to server (don't reactive).

**Comment by MichalW** [comment]
Please check it in the latest version 0.3.1

**Comment by thearabbit** [comment]
Great, Now I'm updating...

**Comment by DanceParty** [comment]
When passing the optionsMethodParams, how do I access that value within the server-side method?

**Comment by DanceParty** [comment]
Figured it out. Thanks.
