### ISSUE TITLE
Some problem with "arrow and tap key".

### ISSUE THREAD

**Issue by thearabbit** [vazco/meteor-universe-autoform-select#24]
The first thanks for your package to help me a lot.
Now it work for arrow key to select item list, but:

![2016-02-02_21-26-33](https://cloud.githubusercontent.com/assets/4495160/12752182/cf5afc52-c9f3-11e5-9352-f802cdaac768.png)
1. If my mouse pointer is on "0004: B", so we can't arrow key on this.
2. When I selected item already, we can't use `tap key` to next input.
3. we can't use `arrow key (-> next)` to reopen the select.

**Comment by MichalW** [comment]
I commited fix for this

**Comment by thearabbit** [comment]
Now work fine for `arrow key`.
But still problem with `tap key` to next input.
It is always reactive value when we use `arrow key` to select the item, I think that it should be on `enter/selected`.

**Comment by MichalW** [comment]
You mean tab key? 
![tab-key](https://cloud.githubusercontent.com/assets/2961245/12780082/1d92274c-ca6c-11e5-97bb-02efffacbbab.png)

**Comment by thearabbit** [comment]
That right, key `tap` to next input!

**Comment by MichalW** [comment]
It works well for me. Can you pase an example?

**Comment by thearabbit** [comment]
Thanks for your helping, I close this.
