### ISSUE TITLE
Alternative to 'related selects' example

### ISSUE THREAD

**Issue by acomito** [vazco/meteor-universe-autoform-select#28]
It seem like using afFieldValueContains (similar to: http://autoform.meteor.com/fieldvalues) is easier to achieve then the "related selects" in the example. 

Maybe worth adding a note to docs? Or is there a downside to this strategy?

great package!

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
