### ISSUE TITLE
Hooks of autoform do not work

### ISSUE THREAD

**Issue by mengnic** [vazco/meteor-universe-autoform-select#3]
Hi, to have my form reactive, I'm relying on the hooks, particularly formToDoc. I set validation="keyup", so I assumed that once I change stuff in universe-select, my hoo formToDoc will be called. However, such an event is never triggered:

```
{{#autoForm collection="Meteor.users" id="step2Form" type="update" doc=user validation="keyup" autosave=true}}
    {{> afQuickField name="profile.conditions" create=true  type="universe-select" multiple=true options=optionsCondition}}

    {{> afQuickField name="profile.tags" create=true  type="universe-select" multiple=true options=symptoms}}

    <div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-default">Reset</button>
    </div>
{{/autoForm}}
```

AutoForm.hooks({
    step2Form: {
        formToDoc: function(doc) {
            // If a new condition is selected, set react var pcDiseaseSel to display disease related information (symptoms)
            console.log('helloe')
            Session.set("pcDiseaseSel", doc.profile.conditions);
            return doc;
        }
    }
});

**Comment by mengnic** [comment]
Also, I found that I cannot retrieve the form values through:

AutoForm.getFieldValue('profile.conditions', 'step2Form')

--> Returns undefined

**Comment by MichalW** [comment]
It is working for me with newest autoform. 
I created new form in demo for you: 
https://github.com/vazco/meteor-universe-autoform-select-demo/commit/23cc49478a5aa4d2b2d6cf51db94f59d0cc43276
