### ISSUE TITLE
universe select clear value on add new in Embeded array of object (autoform) 

### ISSUE THREAD

**Issue by mingliang7** [vazco/meteor-universe-autoform-select#34]
![screenshot from 2016-06-08 08-51-30](https://cloud.githubusercontent.com/assets/5500858/15880389/ff247672-2d56-11e6-97e1-6b0a1713553c.png)

**Comment by thearabbit** [comment]
I have the same problem.
+1

**Comment by pmacom** [comment]
+1

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
