### ISSUE TITLE
select a specific item and add events

### ISSUE THREAD

**Issue by yiyizhai** [vazco/meteor-universe-autoform-select#36]
Hi guys! I'm working with this package generating some tags. Here I got some tags in the input field like this:
![screenshot 2016-06-10 at 10 53 28 am](https://cloud.githubusercontent.com/assets/16868831/15973711/b023bd54-2ef9-11e6-8e66-0e6408d03a2a.png)

I want to be able to click on each item and add some events on the active item. however, I found out that whichever item I clicked, the dropdown box would appear as if i would like to add new tags:
![screenshot 2016-06-10 at 10 55 59 am](https://cloud.githubusercontent.com/assets/16868831/15973776/0afd4510-2efa-11e6-9d7b-8a0d07c4b0e9.png)

Any suggestions how I can add the functions of individually clicking on and selecting one specific item? Thanks a lot

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
