### ISSUE TITLE
How to clear selected or set selected value?

### ISSUE THREAD

**Issue by thearabbit** [vazco/meteor-universe-autoform-select#39]
I would like to clear selected/set selected value, when I have any event on other form object

``` js
{{> afQuickField name="clientId"}}
{{> afQuickField name="productId"}}

----------------------

formTmpl.events({
    'change [name="clientId"]'(event, instance){
        $('[name="productId"]').val('');
        // Or
        $('[name="productId"]').val('General');
    }
});
```

But don't work, Pl help me.

**Comment by macroramesh6** [comment]
same issue!!. I need to clear value which is related o another field.

**Comment by goncalovelosa** [comment]
Same here, but in my case I want to set a initial value, in other autoform types its possible using the value attribute but not when using universe-select.

`{{> afQuickField name="productId" value='initialValue'}}`

**Comment by bluefangs** [comment]
- 1 on this. Currently the jquery way isn't working
  $(#fieldName).val(''); --> does nothing

**Comment by thearabbit** [comment]
Have any solve?

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
