### ISSUE TITLE
Problem with many items on multiple select (don't auto resize).

### ISSUE THREAD

**Issue by thearabbit** [vazco/meteor-universe-autoform-select#40]
Problem with many items on multiple select.
(It don't auto resize for many items)

![2016-06-12_14-51-48](https://cloud.githubusercontent.com/assets/4495160/15989849/6af147be-30ad-11e6-94be-35cdccf6c236.png)

**Comment by barry-w-hill** [comment]
Might help others. My workaround for this was to add the following in my own stylesheet. Not ideal, needs to be option I think.

```
.universe-selectize.selectize-control.multi .selectize-input {
  height: auto !important;
}
```

**Comment by thearabbit** [comment]
Thanks look great.
Could you help me for [#39](https://github.com/vazco/meteor-universe-autoform-select/issues/39l)
