### ISSUE TITLE
How to set options group?

### ISSUE THREAD

**Issue by thearabbit** [vazco/meteor-universe-autoform-select#43]
I would like to set `options group`, pl example

``` js
Smart_Phone
      Iphone
      Samsung
      Nokia
Computer
      Apple
      Dell
```

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
