### ISSUE TITLE
Cannot write in to a field on mobile

### ISSUE THREAD

**Issue by twentyfortysix** [vazco/meteor-universe-autoform-select#49]
When a user taps in to a fields, select items are shown, but no cursor appears and the **keyboard does not show up**. Therefore the user have no chance to write down what he/she is looking for.
That is not a problem when the select box have all possible values listed, but when the list shows just a portion of the values and the rest is called up via method then we have a problem. Plus users have no chance to create their own values, if that is allowed.

This misbehaviour can be seen even in the official demo http://universe-autoform-select.stg.vazco.eu/
Again, select box is shown, but no keyboard pops up.

(JS Console shows no error)

works in:
Android 4.4.4, Chrome 62.0...

does not work:
IOS 9, Chrome 62.0...
IOS 9, safari
Android 4.4.4, Native browser

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
