### ISSUE TITLE
unicode support

### ISSUE THREAD

**Issue by ganzo** [vazco/meteor-universe-autoform-select#5]
Hi,

I cant create new items by unicode. Is there any options?

![selection_004](https://cloud.githubusercontent.com/assets/1132724/8538704/1f5da782-24a3-11e5-9e08-888297935d79.png)

**Comment by MichalW** [comment]
Fixed. Now I used https://github.com/ongoworks/meteor-speakingurl for generate slug

Please check newest version

**Comment by MichalW** [comment]
I also created new options to disable slugs:

<pre>
{{> afFormGroup name="create" create=true <b>createSlug=false</b>}}
</pre>

**Comment by ganzo** [comment]
Thank you.
